"""empty message

Revision ID: 86379a2492b2
Revises: a5cffa318ac2
Create Date: 2024-12-09 19:43:25.819371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86379a2492b2'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('diameter', sa.String(length=50), nullable=False),
    sa.Column('rotation_period', sa.String(length=50), nullable=False),
    sa.Column('orbital_period', sa.String(length=50), nullable=False),
    sa.Column('gravity', sa.String(length=50), nullable=False),
    sa.Column('population', sa.String(length=50), nullable=False),
    sa.Column('climate', sa.String(length=200), nullable=False),
    sa.Column('terrain', sa.String(length=50), nullable=False),
    sa.Column('surface_water', sa.String(length=50), nullable=False),
    sa.Column('residents', sa.String(length=50), nullable=False),
    sa.Column('films', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=200),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    op.drop_table('planet')
    # ### end Alembic commands ###
