"""empty message

Revision ID: fcb462e6a544
Revises: ceaf25ac658c
Create Date: 2025-01-02 22:57:01.848052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb462e6a544'
down_revision = 'ceaf25ac658c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=50), nullable=False),
    sa.Column('mass', sa.String(length=50), nullable=False),
    sa.Column('hair_color', sa.String(length=50), nullable=False),
    sa.Column('skin_color', sa.String(length=50), nullable=False),
    sa.Column('eye_color', sa.String(length=50), nullable=False),
    sa.Column('birth_year', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.Column('films', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('character')
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('people_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('favorite_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'])
        batch_op.drop_column('character_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorite_character_id_fkey', 'character', ['character_id'], ['id'])
        batch_op.drop_column('people_id')

    op.create_table('character',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('height', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('mass', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('birth_year', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('films', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], name='character_planet_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_pkey')
    )
    op.drop_table('people')
    # ### end Alembic commands ###
